spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.106.66.5:8848
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  #不加这句则默认为myisam引擎

    #数据库连接
  datasource:
    url: jdbc:mysql://47.106.66.5:3306/shop-mall?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: bnb_system
    password: bnb_system
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    database: 2
    host: 47.106.66.5
    port: 6379
    password: Kexin@2019#
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms

management:
  endpoint:
    health:
      enabled: true


