spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.106.66.5:8848

  redis:
    database: 2
    host: 47.106.66.5
    port: 6379
    password: Kexin@2019#
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms

security:
  oauth2:
    client:
      client-id: user-client
      client-secret: user-secret-8888
      user-authorization-uri: http://localhost:6001/oauth/authorize
      access-token-uri: http://localhost:6001/oauth/token
    resource:
      jwt:
        key-uri: http://localhost:6001/oauth/token_key
        key-value: dev
#    resource:
#      id: user-client
#      user-info-uri: user-info
    authorization:
      check-token-access: http://localhost:6001/oauth/check_token
