server:
  port: 2001
  servlet:
    context-path: /user

spring:
  application:
    name: user-server
  #ehcache
  cache:
    type: ehcache
    ehcache:
      config: classpath:config/ehcache.xml
  profiles:
    active: dev





