spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.106.66.5:8848

  redis:
    database: 2
    host: 47.106.66.5
    port: 6379
    password: Kexin@2019#
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms

management:
  endpoint:
    health:
      enabled: true



