spring:
  zipkin:
    base-url: http://47.106.66.5:9411
    sleuth:
      sampler:
        percentage: 1.0 #数据收集率，1.0代表收集100%数据
  cloud:
    nacos:
      discovery:
        server-addr: 47.106.66.5:8848
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  #不加这句则默认为myisam引擎

    #数据库连接
  datasource:
    url: jdbc:mysql://47.106.66.5:3306/shop-mall?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: bnb_system
    password: bnb_system
    #druid连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    elasticsearch:
      cluster-nodes: 192.168.0.182:9300,192.168.0.219:9300
      cluster-name: elasticsearch-cluster
      repositories:
        enabled: true



