spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.113.91.40:8848
    #redis
  redis:
    host: localhost
    port: 6379
  data:
    elasticsearch:
      cluster-nodes: 192.168.0.182:9300,192.168.0.219:9300
      cluster-name: elasticsearch-cluster

